# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad437bd907f921cfab256e30f1a795f126d8e5158c7001503b9982b7113512ee7fcacd37ca39727c22ff3fb1090f537c26c4173999c7db02051f9e7bfc9d6d8f

test:
  secret_key_base: 89857d9ae210a52b862ec5123da859e7d6e379660cc97ed9e810b0d4479369b3849c7335411c7049bcc9f758b791dc0248b93ccd4e3eddd28298529ec8b4cc04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 7ae77061722b0401f7bf5f6b61f892e597666356c56dd2cb44a8a17c81cbe46518f56c6b0873efd5398e01901cc706066e6531b44838c1b93270395c1fa49f84
